GET http://localhost:1337/register/

################################

POST http://localhost:1337/api/register/
Content-Type: application/json

{
    "email": "quang@gmail.com",
    "password": "123"
}

################################

POST http://localhost:1337/api/login/
Content-Type: application/json

{
    "email": "quang@gmail.com",
    "password": "123"
}
################################

GET http://localhost:1337/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJCNjYwOSIsImlhdCI6MTY2OTk4MjE4MSwiZXhwIjoxNjY5OTg1NzgxfQ.JTKGLe91x9EqTq7_4CdJn-MCMq6gm-RvoIesFAR-4B8

################################
GET http://localhost:1337/api/mcps
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOiJCNjYwOSIsImlhdCI6MTY2OTk4MjE4MSwiZXhwIjoxNjY5OTg1NzgxfQ.JTKGLe91x9EqTq7_4CdJn-MCMq6gm-RvoIesFAR-4B8